### ISSUE TITLE
HELib support

### ISSUE THREAD

**Issue by taqtiqa-mark** [Crypto-TII/fhegen#7]
Thanks for the effort put into fhegen and for making it open source.

I'd like to know how feasible (effort/expertise) it would be to add support for the HELib?
Specifically, would additional analysis be required, or is all that is required is a mapping from the existing metrics?

Context: My PhD is in Finance and Stats, not cryptography, and I am writing a Rust binding for the HELib with a view to making it available via proc-macros. Hence my interest in your paper.

Also, if such HELib support was able to be added would that be in scope of this project?

Appreciate any insights and suggestions.

**Comment by johannesmono** [comment]
Sorry for the late reply, never saw a notification :(

HElib estimates noise dynamically during execution and somewhat guarantees that, if the execution finishes, your parameters are large enough for a correct result. We would have to emulate HElib's noise model which does not make sense only to generate parameters.
